// <auto-generated />
using System;
using ContabilidadeApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContabilidadeApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250517004517_AttBanco")]
    partial class AttBanco
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ContabilidadeApi.Models.ContaContabil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<int>("LancamentoDebitoCreditoId")
                        .HasColumnType("int");

                    b.Property<string>("Mascara")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NaturezaEnum")
                        .HasColumnType("int");

                    b.Property<int>("Situacao")
                        .HasColumnType("int");

                    b.Property<int>("TipoConta")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("ContaContabil");
                });

            modelBuilder.Entity("ContabilidadeApi.Models.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("datetime2");

                    b.Property<int>("LancamentoContabilId")
                        .HasColumnType("int");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("ContabilidadeApi.Models.HistoricoContabil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Codigo")
                        .HasColumnType("int");

                    b.Property<string>("Descricaio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LancamentoContabilId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("HistoricoContabils");
                });

            modelBuilder.Entity("ContabilidadeApi.Models.LancamentoContabil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescComplementar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<int>("HistoricoContabilId")
                        .HasColumnType("int");

                    b.Property<int>("LancamentoDebitoCreditoID")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<bool>("Zeramento")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("HistoricoContabilId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("LancamentoContabil");
                });

            modelBuilder.Entity("ContabilidadeApi.Models.RelatorioContas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContaContabilId")
                        .HasColumnType("int");

                    b.Property<int>("Relatorio")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContaContabilId")
                        .IsUnique();

                    b.ToTable("RelatorioConta");
                });

            modelBuilder.Entity("ContabilidadeApi.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cargo")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCriacaoToken")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<int>("LancamentoContabilId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("SenhaSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("LancamentoDebitoCredito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContaContabilId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int>("LancamentoContabilId")
                        .HasColumnType("int");

                    b.Property<int?>("LancamentoContabilId1")
                        .HasColumnType("int");

                    b.Property<int>("TipoAcao")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ContaContabilId");

                    b.HasIndex("LancamentoContabilId");

                    b.HasIndex("LancamentoContabilId1");

                    b.ToTable("LancamentoDebitoCredito");
                });

            modelBuilder.Entity("ContabilidadeApi.Models.ContaContabil", b =>
                {
                    b.HasOne("ContabilidadeApi.Models.Empresa", "Empresa")
                        .WithMany("ContaContabils")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("ContabilidadeApi.Models.LancamentoContabil", b =>
                {
                    b.HasOne("ContabilidadeApi.Models.Empresa", "Empresa")
                        .WithMany("LancamentoContabil")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContabilidadeApi.Models.HistoricoContabil", "HistoricoContabil")
                        .WithMany("LancamentoContabil")
                        .HasForeignKey("HistoricoContabilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContabilidadeApi.Models.Usuario", "Usuario")
                        .WithMany("LancamentoContabil")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("HistoricoContabil");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ContabilidadeApi.Models.RelatorioContas", b =>
                {
                    b.HasOne("ContabilidadeApi.Models.ContaContabil", "ContaContabil")
                        .WithOne()
                        .HasForeignKey("ContabilidadeApi.Models.RelatorioContas", "ContaContabilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContaContabil");
                });

            modelBuilder.Entity("ContabilidadeApi.Models.Usuario", b =>
                {
                    b.HasOne("ContabilidadeApi.Models.Empresa", "Empresa")
                        .WithMany("Usuario")
                        .HasForeignKey("EmpresaId");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("LancamentoDebitoCredito", b =>
                {
                    b.HasOne("ContabilidadeApi.Models.ContaContabil", null)
                        .WithMany("LancamentoDebitoCredito")
                        .HasForeignKey("ContaContabilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContabilidadeApi.Models.ContaContabil", "ContaContabil")
                        .WithMany()
                        .HasForeignKey("LancamentoContabilId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ContabilidadeApi.Models.LancamentoContabil", "LancamentoContabil")
                        .WithMany()
                        .HasForeignKey("LancamentoContabilId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ContabilidadeApi.Models.LancamentoContabil", null)
                        .WithMany("LancamentoDebitoCredito")
                        .HasForeignKey("LancamentoContabilId1");

                    b.Navigation("ContaContabil");

                    b.Navigation("LancamentoContabil");
                });

            modelBuilder.Entity("ContabilidadeApi.Models.ContaContabil", b =>
                {
                    b.Navigation("LancamentoDebitoCredito");
                });

            modelBuilder.Entity("ContabilidadeApi.Models.Empresa", b =>
                {
                    b.Navigation("ContaContabils");

                    b.Navigation("LancamentoContabil");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ContabilidadeApi.Models.HistoricoContabil", b =>
                {
                    b.Navigation("LancamentoContabil");
                });

            modelBuilder.Entity("ContabilidadeApi.Models.LancamentoContabil", b =>
                {
                    b.Navigation("LancamentoDebitoCredito");
                });

            modelBuilder.Entity("ContabilidadeApi.Models.Usuario", b =>
                {
                    b.Navigation("LancamentoContabil");
                });
#pragma warning restore 612, 618
        }
    }
}
